export const STUDENT_PROFILE_ASSETS = {
  points: "/images/student/profile/icon-points.svg",
  badgeCup: "/images/student/profile/icon-badge-cup.svg",
  badgeCount: "/images/student/profile/icon-badge-count.svg",
  location: "/images/student/profile/icon-location.svg",
  progress: "/images/student/profile/icon-progress.svg",
  live: "/images/student/profile/icon-live.svg",
  quiz: "/images/student/profile/icon-quiz.svg",
  stations: "/images/student/profile/icon-stations.svg",
  ranking: "/images/student/profile/icon-ranking.svg",
  rankUp: "/images/student/profile/icon-rank-up.svg",
  rankDown: "/images/student/profile/icon-rank-down.svg",
  medals: "/images/student/profile/icon-medals.svg",
  courses: "/images/student/profile/icon-courses.svg",
  prefs: "/images/student/profile/icon-prefs.svg",
  info: "/images/student/profile/icon-info.svg",
  email: "/images/student/profile/icon-email.svg",
  code: "/images/student/profile/icon-code.svg",
  phone: "/images/student/profile/icon-phone.svg",
  school: "/images/student/profile/icon-school.svg",
  calendar: "/images/student/profile/icon-calendar.svg",
  bell: "/images/student/profile/icon-bell.svg",
  edit: "/images/student/profile/icon-edit.svg",
  notifLive: "/images/student/profile/icon-notif-live.svg",
  notifQuiz: "/images/student/profile/icon-notif-quiz.svg",
  notifBadge: "/images/student/profile/icon-notif-badge.svg",
} as const;
